### ISSUE TITLE
Code injection / hook set up

### ISSUE THREAD

**Issue by richfitz** [smbache/loggr#10]
This seems unlikely to pass muster with CRAN; already some obfuscation is required to avoid the unsafe NOTE in `R CMD check`.  Or worse; it will pass and then get archived.

I believe it is possible to use `trace` for this purpose instead, with advantages:
- Less Ripley
- easy temporary disabling with `tracingState`
- simpler deactivation
- don't have to delete `_notify_loggr` from `base`, which is not currently possible
- simpler and more transparent

Implementation would look approximately like this (replacing body of `use_logging`:

``` r
catch_signal <- quote(loggr:::notify_loggr(cond))
catch_stop <- quote(loggr:::notify_loggr(..., call.=call., domain=domain, type="error"))
catch_warning <- quote(loggr:::notify_loggr(..., call.=call., immediate.=immediate., noBreaks.=noBreaks., domain=domain, type="warning"))
suppressMessages({
  trace(base::signalCondition, catch_signal, print=FALSE)
  trace(base::stop, catch_stop, print=FALSE)
  trace(base::warning, catch_warning, print=FALSE)
})
```

and then `set_loggr_hook` becomes unnecessary.  The `unset_loggr_hook` (in PR #9) becomes really simple as it is just a set of `untrace` calls.

I'm happy to work up a PR with a full implementation.

**Comment by smbache** [comment]
If this works, could indeed be nicer! We can try it out..

**Comment by smbache** [comment]
Did you play around with this yet? Is it a problem that a call to untrace will remove the logging?

**Comment by smbache** [comment]
Also, related to trace in general is this feature request https://github.com/smbache/loggr/issues/5

**Comment by richfitz** [comment]
I've not yet as I was hoping to go over #9 first, but haven't had time last week.  This really should be applied on top of #9 if it's going to be applied.

untrace removing the logging seems OK to me - it's not common to call.  Or perhaps there's a danger I don't see.

Are you thinking trace for transactional logging?  So the idea is that a log event is triggered but only added to the log if the command succeeds?  Not sure how that would relate to the above, but then tranactional logging is also completely new to me.

**Comment by smbache** [comment]
Yeah me too; but maybe something like 

``` R
log_monitor(some_function)
```

which would add an event signal when function is called and when it is exited. 

BTW, would you prefer to collaborate directly or indirectly? :)

**Comment by richfitz** [comment]
Whichever way works best for you.  I don't want to barge in on your idea!  So just whatever works.

`trace` seems like a good idea for permanently enabling transactional logging.  Another (non-exclusive) option would be a function that takes arguments like:

```
log_transaction("INFO", "pre message", expr, "post message", "fail message")
```

**Comment by richfitz** [comment]
I've added the trace-based code injection to #9 and it seems to work fine.  Give it a whirl if you get a chance.

**Comment by smbache** [comment]
Wouldn't mind collaboration; I just want some great logging :)

Sounds great with the tracing: will check out when I have some time (a very scarse resource).

**Comment by smbache** [comment]
I think we can close this for now with the current use of trace.
