### ISSUE TITLE
loggr must be attached to work

### ISSUE THREAD

**Issue by richfitz** [smbache/loggr#19]
With changes to `log_info` (in de5cf83c49f8afe7fbcc104ef4f1808e62572cc9), loggr no longer works when not attached:

``` r
loggr::log_file("console")
#2015-07-06 16:23:08.735 - INFO - Activating logging to console
loggr::log_info("foo")
# Error in eval(expr, envir, enclos) : 
#  could not find function "log_with_level"
```

Loading the package fixes this:

``` r
library(loggr)
loggr::log_info("foo")
```

Is this unavoidable with the changes to allow use in pipelines?

**Comment by smbache** [comment]
Indeed; fixed via https://github.com/smbache/loggr/commit/a4d5239c7e93df5a448db45685fd06e8feec3694

I made this change to make each of the logging functions as short as possible and without repeating code. Not sure this kind of redirection is optimal, but the idea was to always have the calling environment be `parent.frame()`.
