### ISSUE TITLE
repeat of log4r?

### ISSUE THREAD

**Issue by Mullefa** [smbache/loggr#7]
Not sure if you are aware of this package: https://github.com/johnmyleswhite/log4r?

It looks like there is at least some cross over.

**Comment by smbache** [comment]
Some, but still differences. Mainly, the idea here is to not have to wrap expressions in order for logger to receive signalled conditions. Has both pros and cons.

**Comment by Mullefa** [comment]
Cool - was just bringing it to your attention. Personally, I like the idea of not having to wrap the logger. Looking forward to a logging package as useful and as game-changing as magrittr ;)

**Comment by Ironholds** [comment]
+1 to Mullefa!

**Comment by smbache** [comment]
That will most likely not happen ;) but thanks.

**Comment by krlmlr** [comment]
logging and futile.logger come to mind, too. Would be nice to have a section in the README.

**Comment by daroczig** [comment]
+1 to @krlmlr -- it would be great to have a (short) section in the README on the difference between `loggr` and e.g. `futile.logger`

**Comment by smbache** [comment]
made a new (and open) issue for this with better title: https://github.com/smbache/loggr/issues/20
